### ISSUE TITLE
Detect night theme

### ISSUE THREAD

**Issue by G07cha** [G07cha/pomodoro#12]
When it used in Ubuntu or OS X with dark menubar icon becomes almost invisible.

**Comment by G07cha** [comment]
Nevermind, on OS X it's working but on Linux distributions currently impossible to detect menu color.

**Comment by alnour-altegani** [comment]
I want to use it in elementary os and its not work . there is no window or errors in the command line except 
>Gtk-Message: Failed to load module "pantheon-filechooser-module"
and it is not related any way

**Comment by G07cha** [comment]
Hi, @alnour-altegani 
First of all, you should create issue about this so we can work on your problem separately. Also here is few points to know:
- Linux is not officially supported(because of [menubar](https://github.com/maxogden/menubar) package)
- No windows should appear when you start application, check menubar for black tomato icon

**Comment by alnour-altegani** [comment]
@G07cha thank you . I will but , it is show the Icon you said in mint (mate desktop) but in elementary is not working .

sorry for the late reply

**Comment by G07cha** [comment]
@alnour-altegani hi, actually the app itself is working, there is just no icon displayed and as a result, you can't open it from anywhere. The workaround for your case could be using dock icon instead but unfortunately, this doesn't display either.
