### ISSUE TITLE
Crashed on "Quit" on Windows 8.1

### ISSUE THREAD

**Issue by tvanantwerp** [G07cha/pomodoro#14]
Just installed the x64 Windows version on Windows 8.1 and gave it a try. When I clicked the "Quit" button during a session, the app crashed with the following error.

![2016-02-06 16_43_49-error](https://cloud.githubusercontent.com/assets/2487968/12869550/1b1992c0-ccf1-11e5-9fa4-107f314fa394.png)

**Comment by G07cha** [comment]
This is known problem and already fixed in #13 I'll release new version today that will contain this fix, reopen if you still expecting this issue after updating to a latest version.

**Comment by G07cha** [comment]
@tvanantwerp v1.4.1 is out

**Comment by tvanantwerp** [comment]
Thanks, works fine now--been wanting a simple pomodoro app like this for a while, and I'm excited to start using it!
