### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by Manoflast3** [G07cha/pomodoro#15]
Not sure if this is an actual issue or not, but considering that it is running in the background, I do not think it should be consuming more memory than Chrome. 

![image](https://cloud.githubusercontent.com/assets/9856478/13092802/e763d616-d4cf-11e5-9090-df0795efd529.png)

I have the latest version of Electron (0.36.7) on Windows 10. After leaving the application on for a couple hours, it consumes nearly 700MB on my system (I did not take a screenshot of this, unfortunately).

**Comment by G07cha** [comment]
Are you sure that you have build with latest version? You need to change `electronVersion` variable in `package.json` and build app. Because in my case it using 180-210 MB for pretty long time.

**Comment by G07cha** [comment]
Just release new version, hope it will solve memory issues.
