### ISSUE TITLE
Bower missing JQueryUI dependency

### ISSUE THREAD

**Issue by noaoh** [G07cha/pomodoro#16]
The compiled/non-binary version of this app appears to lack a JQueryUI bower package, making the settings window is non-functional.  
![screen shot 2016-02-27 at 11 01 10 am](https://cloud.githubusercontent.com/assets/5242057/13374137/86b6f710-dd41-11e5-8c9a-6dbf781fc06e.png)

**Comment by G07cha** [comment]
Nice catch, i just forgot to add `jquery-ui` to `bower.json` when migrating packages
