### ISSUE TITLE
Problem with assets in dev

### ISSUE THREAD

**Issue by petems** [G07cha/pomodoro#18]
Awesome project! I'm trying to adapt some of the code you've written for a similar timer app.

When I run `npm start` it looks like it's not loading the assets and bootstrap CSS:

<img width="386" alt="screenshot 2016-04-08 15 35 40" src="https://cloud.githubusercontent.com/assets/1064715/14387103/a4d9c4d8-fd9f-11e5-9d06-6e3bd86b5c49.png">

Is there anything else I need to run to get it to work?

**Comment by G07cha** [comment]
Seems like you didn't installed bower components, install bower with `npm i -g bower` if you don't have it and run `bower install`

**Comment by petems** [comment]
Cool, sorry I'm a noob when it comes to `npm`, just opened #19 for others like me 😄

**Comment by G07cha** [comment]
@petems yep, that was problem in documentation, thanks for your contribution.
