### ISSUE TITLE
Open customisable window rather than dialog window

### ISSUE THREAD

**Issue by petems** [G07cha/pomodoro#20]
Hi again!

I'm trying to figure out how to make it so when the timer alert is up, it opens a new window with a given HTML file, so you can put in custom content or reminders in as html files. Do you know how to do that?

**Comment by G07cha** [comment]
Thats good idea but unfortunately I didn't had enough time to implement this. You can use same function as for creating [settings window](https://github.com/G07cha/pomodoro/blob/master/src/js/main.js#L116-L127).
