### ISSUE TITLE
windows tray icon color

### ISSUE THREAD

**Issue by brandonmp** [G07cha/pomodoro#24]
Using this in win10. Is there a simple way to change the tray icon color? as of now it's black-on-black & it's making me feel like a goth kid

**Comment by G07cha** [comment]
Hi, @brandonmp 

In next version(which will be released very soon) I'm planning to use the colored icon(green and red) for Windows to prevent this problem.

**Comment by brandonmp** [comment]
awesome, fried green tomatoes in my sys tray :) thanks G. been looking for a good cross-platform hiDPI-friendly pomo timer for awhile, happy to have found this proj

**Comment by G07cha** [comment]
Released new version with colored icon \o/

**Comment by tomo90** [comment]
It doesn't seem to be working for me on Win10. Th tray icon is always black. Am I doing something wrong?
![obrazek](https://github.com/G07cha/pomodoro/assets/1255345/ce906426-937c-4049-886d-877216600acb)

**Comment by G07cha** [comment]
Not at all @tomo90, after some changes we're back to a black icon which should be swapped with white when tray has a darker color. I'll see what I can do.

**Comment by G07cha** [comment]
@tomo90 fixed in [v3.2.3](https://github.com/G07cha/pomodoro/releases/tag/v3.2.3)!

**Comment by tomo90** [comment]
> @tomo90 fixed in [v3.2.3](https://github.com/G07cha/pomodoro/releases/tag/v3.2.3)!

thank you @G07cha!
