### ISSUE TITLE
OS X: Use Retina Icons

### ISSUE THREAD

**Issue by ryanbaer** [G07cha/pomodoro#25]
First of all, this app is great and I wanted to say thank you for putting it together.

Currently the icon is a template icon, which is excellent that you support it. However it doesn't support retina resolution for OS X.
<img width="69" alt="screen shot 2016-08-12 at 4 55 02 pm" src="https://cloud.githubusercontent.com/assets/11914327/17639997/8b1108f6-60ad-11e6-8931-eadfcdad6042.png">

I would've just submitted a PR for this, but the only icon you have is that one in low resolution. Can you add the \@2x.png version? I'm happy to do it if you just provide me a higher resolution version of the icon.

Thanks!

**Comment by G07cha** [comment]
Hi @ryanbaer, thanks for pointing out this issue, I didn't notice that. 

Unfortunately, I didn't found original icon but I have a similar one so I'm going to add 2x version soon. It could take some time because application won't build with latest builder version for some reason.

**Comment by ryanbaer** [comment]
Hey @G07cha, thanks for getting back to me so quickly.
I ended up finding the larger version of the icon in build/. I just submitted a PR with retina support for the menubar as well as the index.html page that uses the icon as well. Let me know what you think :)

**Comment by G07cha** [comment]
Version including retina icons is 2.0.1 released, thanks for your help!
