### ISSUE TITLE
Config File Not Found

### ISSUE THREAD

**Issue by koonse** [G07cha/pomodoro#28]
I downloaded the code and followed the install guide, but am getting a config file not found error, causing the app to not load correctly.

``` bash
npm start

> pomodoro@2.0.1 start /Users/bkoonse/Code/pomodoro
> electron .

{ Error: ENOENT: no such file or directory, open '/Users/bkoonse/Library/Application Support/pomodoro/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at getConfig (/Users/bkoonse/Code/pomodoro/index.js:124:28)
    at Object.<anonymous> (/Users/bkoonse/Code/pomodoro/index.js:32:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/bkoonse/Library/Application Support/pomodoro/config.json' }
Didn't find previous config. Using default settings
```

**Comment by G07cha** [comment]
Hi @koonse, it should happen by default if there is no config file present and this error shown only for debugging purposes. 

Does app not work at all? If you change any settings in the app does it will be saved after application restart?

Also, you can grab prebuild [latest release](https://github.com/G07cha/pomodoro/releases/latest).

**Comment by G07cha** [comment]
Any news?

**Comment by koonse** [comment]
@G07cha I downloaded the prebuild from the website and it works. As for `npm start` it seems now when I run it, a config file is saved somewhere because I no longer see the missing config file warning. But I do get `IOVARendererID property not found` and the app shows a frozen screen.

<img width="343" alt="screen shot 2016-10-19 at 11 20 03 am" src="https://cloud.githubusercontent.com/assets/104258/19531877/2075c97a-95ee-11e6-901e-2d79a78acee6.png">

**Comment by G07cha** [comment]
@koonse, is all dependencies installed correctly(`npm i && bower i`)? The error that you've provided might be a problem with an electron. If after installing dependencies it still doesn't work, could you please post your system configuration(OS version, hardware, etc)?

**Comment by G07cha** [comment]
@koonse, is it worked for you?
