### ISSUE TITLE
How to have pomodoro always visible?

### ISSUE THREAD

**Issue by crystalfp** [G07cha/pomodoro#280]
Issue #39 mentions the option "Show timer in menubar", but current version 3.4.2 settings dialog does not have it.

Or, if there is another method to show the timer value unobtrusively, please let me known.
I'm running on Windows 11 64bits.
Thanks!
mario

**Comment by G07cha** [comment]
Thanks for raising the issue, Mario! Unfortunately, showing any additional text next to the tray icon is only supported on macOS at the moment. To my knowledge, it never worked on any of the Windows versions and from Pomodoro 3.x it always shows timer when possible to make it less confusing, so the option became obsolete.
