### ISSUE TITLE
Add optional audio signal on the end of a period

### ISSUE THREAD

**Issue by G07cha** [G07cha/pomodoro#30]
Something like sound of the message in iOS and it could be toggled in the settings

**Comment by mikaoelitiana** [comment]
I think this can be done using built in electron notification https://github.com/electron/electron/blob/master/docs/api/notification.md. I can have a look at it later.

**Comment by G07cha** [comment]
I was thinking to keep current "Dialog" system as it is because we need an input from user to switch to next phase.
