### ISSUE TITLE
Keep countdown timer active while on break

### ISSUE THREAD

**Issue by taylor-brown** [G07cha/pomodoro#35]
I find it helpful to have a reminder that I should take a break - sometimes I'm so focused I forget to actually take the break after I click the ok button.  If the countdown timer could stay up while it's counting  the break, I'd have less incentive to keep my hands on the keyboard.

**Comment by G07cha** [comment]
Apologies for late reaction, I get where this idea coming from, but the downside is that the timer will keep running if left unintentionally active. I sometimes found myself forgetting about the timer and taking a break in a middle of work period or vice versa. Waiting for user's input gives more control to them as well as makes things much simpler engineering-wise.
