### ISSUE TITLE
Settings button doesn't work since 2.1.0 version

### ISSUE THREAD

**Issue by Cosebdd** [G07cha/pomodoro#36]
I've confirmed this on 2.1.0 and 2.2.0 versions. The button works fine in 2.0 however.
OS: Windows 10

**Comment by G07cha** [comment]
Thanks for reporting and narrowing down a specific version where the issue has occurred, that was very helpful! I just published [v2.2.2](https://github.com/G07cha/pomodoro/releases/tag/v2.2.2) with the fix for it, please let me know if it works or not!

**Comment by Cosebdd** [comment]
Yes, it works fine. Thank you!
