### ISSUE TITLE
Feature request: Timer on the icon

### ISSUE THREAD

**Issue by Perisc0** [G07cha/pomodoro#366]
Show the timer on the app icon at System Tray.

**Comment by G07cha** [comment]
Are you using Windows?

**Comment by Perisc0** [comment]
> Are you using Windows?

Yes, Windows 10 x64

**Comment by G07cha** [comment]
Unfortunately, showing text next to the icon is only supported on macOS right now due to [technical limitations](https://docs.rs/tauri/1.6.1/x86_64-pc-windows-msvc/src/tauri/app/tray.rs.html#649-653).
