### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by saamalik** [G07cha/pomodoro#40]
Would be great to have a _Dark Mode_ setting; would be cool to integrate with OSX Mohave theme (Light vs Dark)

**Comment by G07cha** [comment]
Agree, Electron already has support for detecting a dark theme in Mojave([guide](https://github.com/electron/electron/blob/master/docs/tutorial/mojave-dark-mode-guide.md)).

**Comment by G07cha** [comment]
Implemented in [v3.0.0](https://github.com/G07cha/pomodoro/releases/tag/v3.0.0)
